### ISSUE TITLE
リポジトリの置き場について

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/One_Legged_Robot#4]
いいリポジトリですね。 よく管理されていると思います。 :+1: 
ところで、研究室関係のコードのようなので[open-rdc](https://github.com/open-rdc)に移動しませんか？
その方が情報が一箇所に集中しますし、研究を引き継ぐ人がいた場合にも便利だと思います。

やり方は簡単です。 以下のIssueに手順が書いてあります。
https://github.com/open-rdc/real-robot-battle/issues/1

**Comment by KoheiIzumi** [comment]
@DaikiMaekawa 

open-rdcに移動しようとしたら、移動先の権限がないから出来ないと言われたんだけど、なんか間違ってる操作してるかな？

**Comment by DaikiMaekawa** [comment]
多分open-rdcのメンバじゃないからですね。 
@KoheiIzumi と @victorteesinloong をメンバとして招待したので、メールが届いていると思います。 
承認してからもう一度試してみて下さい。

**Comment by KoheiIzumi** [comment]
@DaikiMaekawa 

ダメみたいっすねー

```
You don't have admin rights to open-rdc
```

**Comment by DaikiMaekawa** [comment]
権限を引き上げてみました。
もう一度試してみて。

**Comment by KoheiIzumi** [comment]
@DaikiMaekawa 

出来ました！

**Comment by DaikiMaekawa** [comment]
確認しました。
このIssueを閉じます。
