### ISSUE TITLE
ハードウェアの情報について

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/One_Legged_Robot#8]
一脚ロボットのCADデータは公開されてましたっけ？

**Comment by KoheiIzumi** [comment]
@DaikiMaekawa 

すっかり忘れてました。ありがとうございます。

これから公開します。

**Comment by DaikiMaekawa** [comment]
ファイルサイズが大きい場合はリポジトリを分けたほうがいいかもしれませんね。

**Comment by KoheiIzumi** [comment]
open-rdc/One_Legged_Robot_Hardwareにコミットしました

文字化けしてるので暇があったら直すそうです

**Comment by DaikiMaekawa** [comment]
おー、STLがブラウザから見れていい感じですね。

https://github.com/open-rdc/One_Legged_Robot_Hardware/blob/master/One_Legged_Robot/Assembly2_.stl

**Comment by DaikiMaekawa** [comment]
確認したので閉じます。
