### ISSUE TITLE
評価のランク付けがうまくいかない問題

### ISSUE THREAD

**Issue by umaibow** [open-rdc/One_Legged_Robot#9]
今回実機での実験の際に題目の問題が発生しました。
実験したプログラムはclustering_gaブランチのsample\pc\genetic_algorithm\test05の中にあるファイルをCMakeでビルドしたものです。

問題の内容としましては、評価値の最大が負の値の中からしか選択されないというものになります。
最大値とその個体の番号を表示することで確認できるようになっています。
それに伴い、ロボットの学習そのものにも影響が出ています。

元のプログラムは同ブランチのgenetic_algorithm\five_paramaterになります。
評価値の算出とランク付けのロジックの変更はしてませんでした。

現段階で自力での解決に至ることができなかったので、お知恵を貸していただければと思っています。
よろしくお願いします。

**Comment by yasuohayashibara** [comment]
残念ながら，コンパイルするとエラーが発生しました．
またソフトウェアの仕様と実行環境が揃えられないので，開発のお手伝いは難しいです．
もう少し症状を分かりやすく説明してくれたら，アドバイスしてあげられるかもしれません．
また，ハードウェアが無くてもどこでも動作するような形に切り分けてくれるとこちらでも症状を確認することができます．
ソフトウェアを開発するときにはモジュールごとの動作を確認するプログラムを用意して，意図した通りに動作するかを確認しながら開発していくことをおすすめします．
その点では動作が怪しいところを切り出して，動作を確認するプログラムを作成することをおすすめします．

**Comment by DaikiMaekawa** [comment]
@KoheiIzumi @umaibow 環境構築に必要な依存パッケージなどを明記しておくと良いと思います。
研究を進める上で、最低限 @yasuohayashibara はこのプログラムの開発環境を持っておいたほうが都合が良いでしょう。 ビルドする上で特に注意すべきこと等ありますか?

**Comment by KoheiIzumi** [comment]
@DaikiMaekawa @yasuohayashibara @umaibow 
おそらくコンパイルできないのは、C++11のコンパイル環境がないからだと思います。
（以前、野崎先輩がC++11のところでコンパイルエラーが出たと報告してくださっています。私の環境ではVS2012なので特に問題はありませんでした。）
解決方法はC++11を使っているのはほんの一部のコードだけなので、そこを修正するか、VS2010以降のバージョンを新しくインストールしてもらうのが早いと思います。
（見当違いだったらすいません・・・）

ビルドする上ではC++11の部分とboostがインストールされていればコンパイルできるはずです。
私の環境は
- Visual Studio 2012 
- Boost 1.54（多少バージョンが違っても大丈夫だと思います）

**Comment by yasuohayashibara** [comment]
泉くんアドバイスありがとう．
私の環境は，以下のとおりです．

・Visual Studio 2008
・Boost 1.48.0
・cmake 3.13

おそらく，泉くんの指摘が正解だと思います．
ロボカップの開発環境として使用しており，あまり変更したくないため，できればソースコードを変更していただいた方が良いです．

主に，以下の２点です．
１）autoを使用した部分
auto epoch = local_adj::utc_to_local(pt::ptime(gg::date(1970, 1, 1)));
２）std::の中の関数が幾つか無いと言われます．
str[i] += std::to_string(angle[i][j]);

**Comment by umaibow** [comment]
@yasuohayashibara 反応遅くなってすみません。
コンパイルエラーの件、対処してみます。

**Comment by yasuohayashibara** [comment]
コンパイルエラーの件，解決していると思いますので閉じます．
